In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

Input: 2 strings X = x_1,...,x_n and Y = y_1,...,y_n

Goal: Find the length of the longest string which is a subsequence of both X & Y

Example:

X = B, C, D, B, C, D, A

Y = A, B, E, C, B, A, B

The length of LCS is 4 (B,C,B,A)

First, we define the sub-problem in words:

For i where i = [0, n],

L(i) = length of LCS between: 

X_1,...,X_i and Y_1,...,Y-i.

Second, state recursive relation (express L(i) in terms fo L(1),...,L(i - 1):

Case when x_i == y_i, then **L(i, j) = 1 + L(i - 1, j - 1)**

Case when x_i != y_i, then **max(L(i - 1, j), L(i, j - 1))**

In [2]:
# Implmenting from ODA seminar:
def oda(X, Y):
    # First break down the strings into ['a', 'b', 'c'] etc.
    x = [i for i in X]
    y = [i for i in Y]

    # Create a matrix that is len(x) + 1 by len(y) + 1
    m = len(x)
    n = len(y)

    dp = np.zeros((m + 1, n + 1), dtype = int)
    # print(dp.shape) # (6, 4)
    # print(dp) # Ok looks good
    # diff = ""
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if x[i - 1] == y[j - 1]:
                dp[i, j] = dp[i - 1, j - 1] + 1
                # diff += x[i - 1] # Not correct! Gotta go back upwards.
            else:
                dp[i, j] = max(dp[i, j - 1], dp[i - 1, j])
    print(dp)
    # print(diff)

    # Trace back to find the LCS :)
    diff = ""
    target_to_return = dp[m, n]
    target = dp[m, n]
    print(target)
    while target != 0:
        up_index = m - 1
        left_index = n - 1
        print("Current Target:", target)
        if dp[up_index, n] > dp[m, left_index]: # element at up index > left index
            print("Going up!")
            m = up_index
        elif dp[up_index, n] < dp[m, left_index]: # element at up index < left index
            print("Going left!")
            n = left_index
        else: # Equal
            print("They are equal. Is the diagonal entry up smaller than target?")
            if dp[up_index, left_index] < target:
                print("Position (" + str(up_index) + "," + str(left_index) + ") is! Letter to append is " + '"' + x[m - 1] + '"') # could also do y[n - 1]
                diff += x[m - 1]
                target = dp[up_index, left_index]
                m = up_index
                n = left_index
            else:
                print("Not smaller than target. Let's just go up") # could also go left. But I chose up :)
                m = up_index
    print("LCS:", diff[::-1])
    return target_to_return

In [3]:
oda("abcde", "abc")

[[0 0 0 0]
 [0 1 1 1]
 [0 1 2 2]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
3
Current Target: 3
Going up!
Current Target: 3
Going up!
Current Target: 3
They are equal. Is the diagonal entry up smaller than target?
Position (2,2) is! Letter to append is "c"
Current Target: 2
They are equal. Is the diagonal entry up smaller than target?
Position (1,1) is! Letter to append is "b"
Current Target: 1
They are equal. Is the diagonal entry up smaller than target?
Position (0,0) is! Letter to append is "a"
LCS: abc


np.int64(3)

In [4]:
oda("BCDBCDA", "ABECBA")

[[0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1]
 [0 0 1 1 2 2 2]
 [0 0 1 1 2 2 2]
 [0 0 1 1 2 3 3]
 [0 0 1 1 2 3 3]
 [0 0 1 1 2 3 3]
 [0 1 1 1 2 3 4]]
4
Current Target: 4
They are equal. Is the diagonal entry up smaller than target?
Position (6,5) is! Letter to append is "A"
Current Target: 3
Going up!
Current Target: 3
Going up!
Current Target: 3
They are equal. Is the diagonal entry up smaller than target?
Position (3,4) is! Letter to append is "B"
Current Target: 2
Going up!
Current Target: 2
They are equal. Is the diagonal entry up smaller than target?
Position (1,3) is! Letter to append is "C"
Current Target: 1
Going left!
Current Target: 1
They are equal. Is the diagonal entry up smaller than target?
Position (0,1) is! Letter to append is "B"
LCS: BCBA


np.int64(4)