In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

Input: 2 strings X = x_1,...,x_n and Y = y_1,...,y_n

Goal: Find the length of the longest string which is a subsequence of both X & Y

Example:

X = B, C, D, B, C, D, A

Y = A, B, E, C, B, A, B

The length of LCS is 4 (B,C,B,A)

First, we define the sub-problem in words:

For i where i = [0, n],

L(i) = length of LCS between: 

X_1,...,X_i and Y_1,...,Y-i.

Second, state recursive relation (express L(i) in terms fo L(1),...,L(i - 1):

Case when x_i == y_i, then **L(i, j) = 1 + L(i - 1, j - 1)**

Case when x_i != y_i, then **max(L(i - 1, j), L(i, j - 1))**

In [2]:
# Implmenting from ODA seminar:
def oda(X, Y):
    # First break down the strings into ['a', 'b', 'c'] etc.
    x = [i for i in X]
    y = [i for i in Y]

    # Create a matrix that is len(x) + 1 by len(y) + 1
    m = len(x)
    n = len(y)

    dp = np.zeros((m + 1, n + 1), dtype = int)
    # print(dp.shape) # (6, 4)
    # print(dp) # Ok looks good
    diff = ""
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if x[i - 1] == y[j - 1]:
                dp[i, j] = dp[i - 1, j - 1] + 1
                diff += x[i - 1]
            else:
                dp[i, j] = max(dp[i, j - 1], dp[i - 1, j])
    print(dp)
    print(diff)
    return dp[m, n]
oda("abcde", "abc")

[[0 0 0 0]
 [0 1 1 1]
 [0 1 2 2]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
abc


np.int64(3)