In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

Given weights, value, and capacity.

In [12]:
def ks(w, v, c):
    # Create a matrix that is len(x) + 1 by len(y) + 1
    m = len(w)
    # n = len(v)

    dp = np.zeros((m + 1, c + 1), dtype = int)

    for i in range(1, m + 1):
        for j in range(1, c + 1):
            if w[i - 1] <= j:
                dp[i, j] = max(v[i - 1] + dp[i - 1, j - w[i - 1]], dp[i - 1, j])
                # Which is more valuable? As is or if we remove the weight that is equivalent to the current weight and add it's value?
            else:
                dp[i, j] = dp[i - 1, j] # Doesn't fit. So even if it is worth an infinite amount it can't be added. So just move down the value from whatever is above it.
    print(dp)

    # Iterate backwards to find the items
    i = m
    j = c
    items = []
    while dp[i, j] != 0:
        if dp[i - 1, j] != dp[i, j] and dp[i, j - 1] != dp[i, j]:
            i = i - 1
            j = j - 1
            items.append(i - 1)
        elif dp[i - 1, j] > dp[i, j - 1]:
            # move up
            i = i - 1
        elif 
    return dp[m, c]

In [13]:
v = [15, 10, 8, 1]
w = [15, 12, 10, 5]
c = 22
ks(w, v, c)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 15 15 15 15 15 15 15 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 10 10 10 15 15 15 15 15 15 15 15]
 [ 0  0  0  0  0  0  0  0  0  0  8  8 10 10 10 15 15 15 15 15 15 15 18]
 [ 0  0  0  0  0  1  1  1  1  1  8  8 10 10 10 15 15 15 15 15 16 16 18]]


np.int64(18)

In [14]:
v = [2, 2, 4, 1]
w = [5, 1, 1, 4]
c = 5
ks(w, v, c)

[[0 0 0 0 0 0]
 [0 0 0 0 0 2]
 [0 2 2 2 2 2]
 [0 4 6 6 6 6]
 [0 4 6 6 6 6]]


np.int64(6)