In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

Given weights, value, and capacity.

In [55]:
def ks(w, v, c):
    # Create a matrix that is len(x) + 1 by len(y) + 1
    m = len(w)
    # n = len(v)

    dp = np.zeros((m + 1, c + 1), dtype = int)
    for i in range(1, m + 1):
        for j in range(1, c + 1):
            if w[i - 1] <= j:
                dp[i, j] = max(v[i - 1] + dp[i - 1, j - w[i - 1]], dp[i - 1, j])
                # dp[i, j] = max(v[i - 1] + dp[i - 1, j - w[i - 1]], dp[i - 1, j]) # Broke it down into the if statements above.
                # Which is more valuable? As is or if we remove the weight that is equivalent to the current weight and add it's value?
            else:
                dp[i, j] = dp[i - 1, j] # Doesn't fit. So even if it is worth an infinite amount it can't be added. So just move down the value from whatever is above it.
    print(dp)
    return dp[m, c]

In [56]:
v = [15, 10, 8, 1]
w = [15, 12, 10, 5]
c = 22
ks(w, v, c)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 15 15 15 15 15 15 15 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 10 10 10 15 15 15 15 15 15 15 15]
 [ 0  0  0  0  0  0  0  0  0  0  8  8 10 10 10 15 15 15 15 15 15 15 18]
 [ 0  0  0  0  0  1  1  1  1  1  8  8 10 10 10 15 15 15 15 15 16 16 18]]


np.int64(18)

In [58]:
v = [2, 2, 4, 1]
w = [5, 1, 1, 3]
c = 5
ks(w, v, c)

[[0 0 0 0 0 0]
 [0 0 0 0 0 2]
 [0 2 2 2 2 2]
 [0 4 6 6 6 6]
 [0 4 6 6 6 7]]


np.int64(7)

In [45]:
def ks(w, v, c):
    # Create a matrix that is len(x) + 1 by len(y) + 1
    m = len(w)
    # n = len(v)

    dp = np.zeros((m + 1, c + 1), dtype = int)
    parent = []
    max_item = -1
    max_val = 0
    for i in range(1, m + 1):
        parent.append(-1)
        appended = False
        for j in range(1, c + 1):
            if w[i - 1] <= j:
                if v[i - 1] + dp[i - 1, j - w[i - 1]] > dp[i - 1, j]:
                    dp[i, j] = v[i - 1] + dp[i - 1, j - w[i - 1]]
                    # print(i - 1)
                    if not appended:
                        parent[-1] = i - 2
                        appended = True
                    if dp[i, j] > max_val:
                        max_val = dp[i, j]
                        max_item = i - 1
                else:
                    dp[i, j] = dp[i - 1, j]
                # dp[i, j] = max(v[i - 1] + dp[i - 1, j - w[i - 1]], dp[i - 1, j]) # Broke it down into the if statements above.
                # Which is more valuable? As is or if we remove the weight that is equivalent to the current weight and add it's value?
            else:
                dp[i, j] = dp[i - 1, j] # Doesn't fit. So even if it is worth an infinite amount it can't be added. So just move down the value from whatever is above it.
    print(dp)
    print(parent)
    sequence = []
    current = max_item
    while current != 0:
        sequence.append(current)
        current = parent[current]
    print(sequence[::-1])
    return dp[m, c]

In [46]:
v = [15, 10, 8, 1]
w = [15, 12, 10, 5]
c = 22
ks(w, v, c)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 15 15 15 15 15 15 15 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 10 10 10 15 15 15 15 15 15 15 15]
 [ 0  0  0  0  0  0  0  0  0  0  8  8 10 10 10 15 15 15 15 15 15 15 18]
 [ 0  0  0  0  0  1  1  1  1  1  8  8 10 10 10 15 15 15 15 15 16 16 18]]
[-1, 0, 1, 2]
[1, 2]


np.int64(18)

In [47]:
v = [2, 2, 4, 1]
w = [5, 1, 1, 3]
c = 5
ks(w, v, c)

[[0 0 0 0 0 0]
 [0 0 0 0 0 2]
 [0 2 2 2 2 2]
 [0 4 6 6 6 6]
 [0 4 6 6 6 7]]
[-1, 0, 1, 2]
[1, 2, 3]


np.int64(7)