In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

## With repetition (figured out without watching lecture first!)

In [22]:
def ks(w, v, c):
    # Create a matrix that is len(x) + 1 by len(y) + 1
    m = len(w)
    # n = len(v)

    dp = np.zeros((m + 1, c + 1), dtype = int)
    for i in range(1, m + 1):
        for j in range(1, c + 1):
            if w[i - 1] <= j:
                dp[i, j] = max(dp[i - 1, j], v[i - 1] + dp[i, j - w[i - 1]])
                # dp[i, j] = max(v[i - 1] + dp[i - 1, j - w[i - 1]], dp[i - 1, j]) # Broke it down into the if statements above.
                # Which is more valuable? As is or if we remove the weight that is equivalent to the current weight and add it's value?
                #1. Diagonal down. Remove equivalent weight and add new item with same weight with more value. # Don't need this apparently: v[i - 1] + dp[i - 1, j - w[i - 1]], 
                #2. Use what's higher (just use what's above: i - 1)
                #3. Add on to what's in the bag already <-
            else:
                dp[i, j] = dp[i - 1, j] # Doesn't fit. So even if it is worth an infinite amount it can't be added. So just move down the value from whatever is above it.
    print(dp)
    return dp[m, c]

In [23]:
v = [2, 2, 4, 1]
w = [5, 1, 1, 3]
c = 5
ks(w, v, c)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  2]
 [ 0  2  4  6  8 10]
 [ 0  4  8 12 16 20]
 [ 0  4  8 12 16 20]]


np.int64(20)

In [24]:
v = [15, 10, 8, 1]
w = [15, 12, 10, 5]
c = 22
ks(w, v, c)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 15 15 15 15 15 15 15 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 10 10 10 15 15 15 15 15 15 15 15]
 [ 0  0  0  0  0  0  0  0  0  0  8  8 10 10 10 15 15 15 15 15 16 16 18]
 [ 0  0  0  0  0  1  1  1  1  1  8  8 10 10 10 15 15 15 15 15 16 16 18]]


np.int64(18)

In [25]:
v = [2, 3, 1, 2]
w = [5, 2, 1, 3]
c = 5
ks(w, v, c)

[[0 0 0 0 0 0]
 [0 0 0 0 0 2]
 [0 0 3 3 6 6]
 [0 1 3 4 6 7]
 [0 1 3 4 6 7]]


np.int64(7)

## There's a simpler solution with smaller space. O(B) space instead of a 2D table.

In [38]:
def ks_o(w, v, c):
    dp = []
    for b in range(c + 1):
        dp.append(0)
        for i in range(len(w)):
            if w[i] <= b:
                if v[i] + dp[b - w[i]] > dp[b]:
                    dp[b] = v[i] + dp[b - w[i]]
    print(dp)
    return dp[-1]

In [39]:
v = [2, 3, 1, 2]
w = [5, 2, 1, 3]
c = 5
ks_o(w, v, c)

[0, 1, 3, 4, 6, 7]


7

In [40]:
v = [2, 2, 4, 1]
w = [5, 1, 1, 3]
c = 5
ks_o(w, v, c)

[0, 4, 8, 12, 16, 20]


20

## Implement Tracing

In [81]:
def ks_o(w, v, c):
    dp = []
    sb = []
    for b in range(c + 1):
        dp.append(0)
        sb.append(0)
        for i in range(len(w)):
            if w[i] <= b:
                if v[i] + dp[b - w[i]] > dp[b]:
                    # print("weight", w[i], "value", v[i], "adds on to capacity", b, "contributes to", b - w[i], "so total", v[i] + dp[b - w[i]])
                    dp[b] = v[i] + dp[b - w[i]]
                    sb[b] = i
    print("table", dp)
    print("tracking", sb)
    b = c
    chosen_items = []
    while b > 0:
        i = sb[b]       # last item index used for capacity b
        chosen_items.append(i)
        b -= w[i]       # reduce capacity by the weight of that item

    print("chosen items", chosen_items)  # sequence of chosen item indices
    return dp[-1]

In [82]:
v = [2, 2, 4, 1]
w = [5, 1, 1, 3]
c = 5
ks_o(w, v, c)

table [0, 4, 8, 12, 16, 20]
tracking [0, 2, 2, 2, 2, 2]
chosen items [2, 2, 2, 2, 2]


20

In [83]:
v = [2, 3, 1, 2]
w = [5, 2, 1, 3]
c = 5
ks_o(w, v, c)

table [0, 1, 3, 4, 6, 7]
tracking [0, 2, 1, 1, 1, 1]
chosen items [1, 1, 2]


7

In [84]:
v = [2, 1, 3, 2]
w = [5, 1, 2, 3]
c = 5
ks_o(w, v, c)

table [0, 1, 3, 4, 6, 7]
tracking [0, 1, 2, 1, 2, 1]
chosen items [1, 2, 2]


7