In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

In [16]:
def cmm(X):
    num_matrix = len(X)//2
    print(num_matrix)
    table = np.zeros((num_matrix, num_matrix))
    for i in range(num_matrix - 1):
        for j in range(num_matrix - 1 - i):
            k = j + i + 1
            table[j, k] = np.inf
            for l in range(j, k):
                cost = table[j, l] + table[l + 1, k] + X[2 * j] * X[2 * l + 1] * X[2 * k + 1]
                if cost < table[j, k]:
                    table[j, k] = cost
    print(table)
    return table[0, num_matrix - 1]

In [17]:
X = [2, 3, 3, 4, 4, 5, 5, 6]

In [18]:
cmm(X)

4
[[  0.  24.  64. 124.]
 [  0.   0.  60. 150.]
 [  0.   0.   0. 120.]
 [  0.   0.   0.   0.]]


np.float64(124.0)