In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import time

## With repetition

In [18]:
def ks(w, v, c):
    # Create a matrix that is len(x) + 1 by len(y) + 1
    m = len(w)
    # n = len(v)

    dp = np.zeros((m + 1, c + 1), dtype = int)
    for i in range(1, m + 1):
        for j in range(1, c + 1):
            if w[i - 1] <= j:
                dp[i, j] = max(v[i - 1] + dp[i - 1, j - w[i - 1]], dp[i - 1, j], v[i - 1] + dp[i, j - w[i - 1]])
                # dp[i, j] = max(v[i - 1] + dp[i - 1, j - w[i - 1]], dp[i - 1, j]) # Broke it down into the if statements above.
                # Which is more valuable? As is or if we remove the weight that is equivalent to the current weight and add it's value?
                #1. Diagonal down. Remove equivalent weight and add new item with same weight with more value.
                #2. Use what's higher (just use what's above: i - 1)
                #3. Add on to what's in the bag already <-
            else:
                dp[i, j] = dp[i - 1, j] # Doesn't fit. So even if it is worth an infinite amount it can't be added. So just move down the value from whatever is above it.
    print(dp)
    return dp[m, c]

In [19]:
v = [2, 2, 4, 1]
w = [5, 1, 1, 3]
c = 5
ks(w, v, c)

[[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  2]
 [ 0  2  4  6  8 10]
 [ 0  4  8 12 16 20]
 [ 0  4  8 12 16 20]]


np.int64(20)

In [20]:
v = [15, 10, 8, 1]
w = [15, 12, 10, 5]
c = 22
ks(w, v, c)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 15 15 15 15 15 15 15 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 10 10 10 15 15 15 15 15 15 15 15]
 [ 0  0  0  0  0  0  0  0  0  0  8  8 10 10 10 15 15 15 15 15 16 16 18]
 [ 0  0  0  0  0  1  1  1  1  1  8  8 10 10 10 15 15 15 15 15 16 16 18]]


np.int64(18)